
export const INIT = "INIT";
export const OTHER_USER_DESIGNS = "OTHER_USER_DESIGNS";
export const SETTINGS = "SETTINGS";
export const HISTORY = "HISTORY";
export const OBJECTS = "OBJECTS";
export const FONTS = "FONTS";
export const SVG = "SVG";
export const USER_UPLOADS = "USER_UPLOADS";
export const USER_UPLOADS_FILES_LINKS = "USER_UPLOADS_FILES_LINKS";
export const USER_OVVERIDE_UPLOADS_FILES_LINKS = "USER_OVVERIDE_UPLOADS_FILES_LINKS";
export const STORE = "STORE";
export const STORE_DESIGN = "STORE_DESIGN";
export const USER_NEW_DESIGN = "USER_NEW_DESIGN";
export const CHANGE_CURRENT_DESIGN = "CHANGE_CURRENT_DESIGN";
export const DESIGN_MANAGER_SAVE_CONTROL = "DESIGN_MANAGER_SAVE_CONTROL";
export const LAST_DESIGN_NUMBER = "LAST_DESIGN_NUMBER";
export const CHANGE_INDEX_DESIGN = "CHANGE_INDEX_DESIGN";


export const DESIGN = "DESIGN";
export const DESIGN_COLLECTION = "DESIGN_COLLECTION";
export const OVERRIDE_DESIGN = "OVERRIDE_DESIGN";
export const INITS_ASSETS = "INITS_ASSETS";
export const PHOTOS_ASSETS = "PHOTOS_ASSETS";
export const LOGOS_ASSETS = "LOGOS_ASSETS";
export const STICKERS_ASSETS = "STICKERS_ASSETS";
export const SHAPES_ASSETS = "SHAPES_ASSETS";
export const ALL_ASSETS = "ALL_ASSETS";
export const STICKERS_PACKS_LOADED = "STICKERS_PACKS_LOADED";

export const ASSET_CATEGORY = "ASSET_CATEGORY";





export const SET_OBJECTS = "SET_OBJECTS";
export const SET_POPUP = "SET_POPUP";
export const SET_ASSET_TAB = "SET_ASSET_TAB";
export const SET_USER = "SET_USER";

/* LoaderActionsReducer.js */
export const SET_ALL_ASSET_TAB_LOADER = "SET_ALL_ASSET_TAB_LOADER";
export const SET_LOGO_TAB_LOADER = "SET_LOGO_TAB_LOADER";
export const SET_STICKER_TAB_LOADER = "SET_STICKER_TAB_LOADER";
export const SET_USERDESIGN_LOADER = "SET_USERDESIGN_LOADER";
export const SET_CANVAS_LOADER = "SET_CANVAS_LOADER";


export const ADD_HISTORY = "ADD_HISTORY";
export const REMOVE_HISTORY = "REMOVE_HISTORY";

export const ADD_SVG_LOGOS = "ADD_SVG_LOGOS";


/* ObjectReducer.js */
export const ADD_OBJECTS = "ADD_OBJECTS";
export const REMOVE_OBJECTS = "REMOVE_OBJECTS";
export const SET_OBJECT_ID = "SET_OBJECT_ID";
export const SET_SELECTION_OBJECTS = "SET_SELECTION_OBJECTS";



export const USER_DESIGN = "USER_DESIGN";
export const DESIGN_TYPE_REDUCER = "DESIGN_TYPE_REDUCER";



/* Modals */
export const SET_STORE_PUBLISH_MODAL = "SET_STORE_PUBLISH_MODAL";
export const SET_MESSAGE_PUBLISH_MODAL = "SET_MESSAGE_PUBLISH_MODAL";
export const SET_ADD_COLLECTION_MODAL = "SET_ADD_COLLECTION_MODAL";
export const SET_EXPORT_MODAL = "SET_EXPORT_MODAL";
export const SET_SHOW_DESIGNS_MODAL = "SET_SHOW_DESIGNS_MODAL";
